### PR TITLE
#460 my account additions

### PR DESCRIPTION
**Pull request by patternleaf**
Some work for #460. Styling probably needs some more thought. Geoff, please review and comment when you get a chance. thanks.

### CODE REVIEW

**Comment by patternleaf** [comment]
@ghing alright, i gave this a shot. i agree with the general pattern, by the way. still feel like i'm groping around in Django to use the right mixins, classes, patterns, etc. please review and provide comments when you get a chance.

also, lower priority, but it would be nice to be able to load the confirmation view in a modal box on a page rather than have the entire page reload for the confirmation step. this would require having a stripped-down view that did not include base.html's chrome. could either do iframe (requiring loaded stylesheets in the stripped-down view) or AHAH-style. thoughts on this?

**Comment by ghing** [comment]
I'll take a look at this later today.  Personally, I'd do the scripted confirmation even lower fidelity. Use jQuery to capture clicks on the links, show a plain, old Javascript `confirm()` dialog, and if the user confirms, make an async post to the delete URL.

Also, while we're on the subject of IFRAMing or AHAHing views that should also work as normal views, I wrote a Django middleware that will take any view and extract content from it based on a CSS selector, so visiting `/some/path/on/floodlight?extract=true&selector=#main` would select return a page with only the contents of the the element with id of main rather than the entire theme.  You still get the overhead of Django rendering the entire template, but not the overhead of the browser having to render the HTML and download any assets.  I don't think we need to use the middleware functionality for this feature, but I wanted to let you know that it's there if you ever need to use it

**Comment by ghing** [comment]
A few things:
- The confirmation step should have a page title (use the `head_title` block)
- Deleted stories should be hidden from the stories list
- Clean up alignment of the table.  Maybe the unpublish/delete buttons should be in the same column as the build button instead of being in the `status` column
- Style the build link (maybe as an orange button)

**Comment by patternleaf** [comment]
ok, those items are in the branch. 

> Personally, I'd do the scripted confirmation even lower fidelity. Use jQuery to capture clicks on the links, show a plain, old Javascript confirm() dialog, and if the user confirms, make an async post to the delete URL.

one issue with asynch would be updating the list view to reflect the new state following the operation. with your middleware it should be pretty straightforward to pose a quick, nicely-rendered modal dialog. i'm inclined to give that a shot.

**Comment by ghing** [comment]
This looks good. I'll be merging in a second.  For now, let's now worry about a popup confirm, just because I feel like there are bigger fish to fry.

**Pull request merged**
