### PR TITLE
475 share button

### PR DESCRIPTION
**Pull request by patternleaf**
Initial work on share button. Installed/working in viewer and story detail view. Some styling refinement in order. Addresses #475.

### CODE REVIEW

**Comment by ghing** [comment]
This looks good so far and pretty close to being done.

It doesn't look like the Twitter sharing button in the AddThis widget is picking up the story URL in the Tweet. 

Also, this should be wired into the final step of the Story Builder as well, but let's worry about that after you clean up the jQuery version selection and get Twitter to pick up the URL.

**Comment by patternleaf** [comment]
hm: i wasn't able to reproduce the twitter issue. it appeared to be working on deploy. what exactly was the behavior you saw?

let me know if i should take a look at wiring the button into the build/share step of the story builder. presumably it would live where there is now the URL link under "Let your story be heard!"?

**Comment by ghing** [comment]
I'll try to replicate the Twitter issue and describe it in more detail.

Go ahead and wire that button into the build/share step.  It will live
where you described (where there is now the URL link under "Let your story
be heard!")

On Wed, Nov 28, 2012 at 9:39 AM, Eric Miller notifications@github.comwrote:

> hm: i wasn't able to reproduce the twitter issue. it appeared to be
> working on deploy. what exactly was the behavior you saw?
> 
> let me know if i should take a look at wiring the button into the
> build/share step of the story builder. presumably it would live where there
> is now the URL link under "Let your story be heard!"?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/PitonFoundation/atlas/pull/484#issuecomment-10807106.

## 

Geoffrey Hing
geoffhing@gmail.com
773.969.6436
http://geoff.terrorware.com/
Twitter: @geoffhing

**Comment by ghing** [comment]
I wasn't able to replicate the Twitter issue on dev either.  It must be specific to local development.  I'm going to go ahead and merge this.

**Pull request merged**
