### PR TITLE
Make messages color darker (#533).

### PR DESCRIPTION
**Pull request by patternleaf**
Use medium-gray gray value for ul.messages rather than light-gray.
Difficult to be certain that this change won't make some other use
of ul.messages unreadable, but a brief search didn't turn up anything
obvious, and the change in value is smallish.

### CODE REVIEW

**Comment by ghing** [comment]
I wonder if it makes sense to move the border from the `ul.messages` element to the `li` element? That way we could use the class on the li element (e.g. `li.success`) to provide more semantic context and allow for multiple messages.  This is what the markup of the message in particular looks like:

```
<ul class="messages">
<li class="success">Thanks! Your message has been submitted to the site administrators</li>
</ul>
```

**Comment by patternleaf** [comment]
Hm. Well we're already doing something like that but with text color rather than border color. [Here, for example](https://github.com/PitonFoundation/atlas/blob/develop/static/less/misc.less#L49). Are you suggesting moving the color change to border instead of text?

**Comment by ghing** [comment]
@patternleaf, I'm suggesting moving the border styles to the li element instead of the ul element and have the color change reflected in the font color, border color and background color. That way, if there are multiple messages of different types, they can be easily distinguished from each other.

**Comment by ghing** [comment]
@patternleaf, I think it's just easier for me to do this than try to explain what I mean. I'm going to merge your color styling changes and then add some commits.  I'll let you know when I'm done so you can see my approach.

**Comment by ghing** [comment]
@patternleaf, 5326bd6fb1da360ac3d0ae6d6bcccdbc37c069f3 is what I was talking about. This should be good now.

**Pull request merged**
