### PR TITLE
821 embed widget template

### PR DESCRIPTION
**Pull request by patternleaf**
This contains the work on the embed widget template to date. Seems mostly ok in Safari, FF, Chrome, and IE8. Generally some more tweaking of breakpoints and layout might be appropriate.

Please review the commit comments and let me know if you have any questions.

One outstanding issue: in IE8, media queries are not working when the widget is in an iframe (they do work when widget URL is loaded directly). Currently using css3-mediaqueries.js because its setup was simpler than respond.js, however respond.js may get this working. If not, the best route might be some simple jQuery-driven dimensions check and CSS class additions.

### CODE REVIEW

**Comment by patternleaf** [comment]
Crap—sorry, just realized this should've gone to the 741-embed_widget branch, no?

**Comment by ghing** [comment]
@patternleaf Yes, this should go to the 741-embed_widget branch.  I think you can change this, or just close and open a new one.  Also, can you merge in my changes you merged in from the #824 changes into your #741 branch before sending the new pull request (unless we need to talk about the #824 changes).

**Comment by patternleaf** [comment]
@ghing to clarify: are you looking for a single pull request for 741 which already contains both 824 and 821 merged in?

**Comment by ghing** [comment]
Yes, if that's not too much of a pain for you.

-Geoff

On Thu, Sep 19, 2013 at 2:22 PM, Eric Miller notifications@github.comwrote:

> @ghing https://github.com/ghing to clarify: are you looking for a
> single pull request for 741 which already contains both 824 and 821 merged
> in?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/PitonFoundation/atlas/pull/865#issuecomment-24766235
> .

## 

Geoffrey Hing
geoffhing@gmail.com
773.969.6436
http://geoff.terrorware.com/
Twitter: @geoffhing

**Pull request closed without merging**
